/**
 * Barrel re-export for Phosphor icons.
 *
 * Always import icons from `@/components/icons` — never directly from
 * `@phosphor-icons/react` or `@phosphor-icons/react/dist/ssr`.
 *
 * The `/dist/ssr` entry avoids `React.createContext` at module scope,
 * which crashes in React Server Components where the vendored React
 * does not expose `createContext`.
 */

export type { Icon } from '@phosphor-icons/react/dist/ssr';

export {
  ArrowClockwise,
  ArrowLeft,
  ArrowRight,
  ArrowsClockwise,
  ArrowSquareOut,
  Bell,
  Buildings,
  CaretDown,
  CaretLeft,
  CaretRight,
  Check,
  CheckCircle,
  CheckSquare,
  Circle,
  CircleDashed,
  CircleNotch,
  ClipboardText,
  Clock,
  CloudArrowUp,
  Coins,
  Copy,
  CopySimple,
  CreditCard,
  CurrencyCircleDollar,
  CurrencyNgn,
  DeviceMobile,
  DotsThree,
  EnvelopeSimple,
  Eye,
  EyeSlash,
  Files,
  FileText,
  Funnel,
  Gear,
  GearSix,
  Globe,
  GraduationCap,
  HandCoins,
  Handshake,
  House,
  IdentificationCard,
  Info,
  Lightning,
  Link,
  List,
  LockKey,
  MagnifyingGlass,
  MapPin,
  Medal,
  Money,
  Moon,
  PaperPlaneTilt,
  Plus,
  Pulse,
  Question,
  Shield,
  ShieldCheck,
  ShieldSlash,
  ShieldWarning,
  Sparkle,
  SpinnerGap,
  Trash,
  Tray,
  TrendUp,
  Trophy,
  User,
  UserCircle,
  UserFocus,
  UserPlus,
  Users,
  Wallet,
  Warning,
  WarningCircle,
  X,
  XCircle,
} from '@phosphor-icons/react/dist/ssr';
