/**
 * Barrel re-export for Phosphor icons.
 *
 * Always import icons from `@/components/icons` — never directly from
 * `@phosphor-icons/react` or `@phosphor-icons/react/dist/ssr`.
 *
 * The `/dist/ssr` entry avoids `React.createContext` at module scope,
 * which crashes in React Server Components where the vendored React
 * does not expose `createContext`.
 */

export type { Icon } from '@phosphor-icons/react';
export type { IconProps } from '@phosphor-icons/react';

export {
  ArrowClockwise,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowsClockwise,
  ArrowsOut,
  ArrowSquareOut,
  Bell,
  BookOpenText,
  Briefcase,
  Buildings,
  CalendarBlank,
  CaretDown,
  CaretLeft,
  CaretRight,
  ChartBar,
  Check,
  CheckCircle,
  CheckSquare,
  Circle,
  CircleDashed,
  CircleNotch,
  ClipboardText,
  Clock,
  ClockCounterClockwise,
  CloudArrowUp,
  Coins,
  Copy,
  CopySimple,
  CreditCard,
  CurrencyCircleDollar,
  CurrencyNgn,
  Database,
  Desktop,
  DeviceMobile,
  DeviceTablet,
  DotsThree,
  DotsThreeVertical,
  DownloadSimple,
  Envelope,
  EnvelopeSimple,
  Eye,
  EyeSlash,
  File,
  FilePdf,
  Files,
  FileText,
  Funnel,
  Gear,
  GearSix,
  Globe,
  GraduationCap,
  HandCoins,
  Handshake,
  Headset,
  House,
  IdentificationCard,
  Info,
  Kanban,
  Key,
  Lightning,
  ListChecks,
  Link,
  List,
  LockKey,
  MagnifyingGlass,
  MapPin,
  Medal,
  Money,
  Moon,
  Palette,
  PaperPlaneTilt,
  PaperPlaneRight,
  Percent,
  Receipt,
  Plus,
  Pulse,
  Question,
  Scroll,
  SealCheck,
  Shield,
  ShieldCheck,
  ShieldSlash,
  SignOut,
  ShieldWarning,
  Sparkle,
  SpinnerGap,
  Stamp,
  Sun,
  Trash,
  Tray,
  TrendUp,
  Trophy,
  UploadSimple,
  User,
  UserCircle,
  UserFocus,
  UserPlus,
  Users,
  Wallet,
  Warning,
  WarningCircle,
  WhatsappLogo,
  X,
  XCircle,
} from '@phosphor-icons/react/dist/ssr';
