/** Marketing and public page copy — about, pricing, terms, privacy, contact */

export const marketingCopy = {
  about: {
    title: 'About Doculet',
    subtitle: 'Connecting Nigerian students, sponsors, and US universities with verified proof-of-funds.',
    mission: {
      title: 'Our mission',
      body: 'Every year, thousands of Nigerian students lose their US university spots — not because the money is not there, but because bank statements alone are not trusted. Doculet verifies identity, bank balances, and sponsor commitments, then issues a cryptographically sealed certificate that admissions offices can verify in one click.',
    },
    values: [
      { title: 'Trust', body: 'We verify at source. BVN, live bank APIs, and sponsor attestation — not PDFs.' },
      { title: 'Privacy', body: 'NDPR compliant. No passwords stored. You control what is shared.' },
      { title: 'Speed', body: 'Tier 2 verification in under 24 hours. Tier 3 in 2–5 business days.' },
    ],
    cta: 'Get your certificate',
    ctaHref: '/signup',
  },
  pricing: {
    title: 'Pricing',
    subtitle: 'Simple, transparent pricing for students and institutions.',
    student: {
      title: 'Students',
      certFee: '₦80,000',
      certFeeLabel: 'Per certificate',
      renewalLabel: 'Renewal',
      renewalFee: '₦40,000',
      features: ['Identity verification (BVN/NIN)', 'Bank connection or PDF upload', 'Sponsor invitation (Tier 3)', 'Doculet Seal certificate', 'Share link for universities'],
    },
    university: {
      title: 'Universities',
      free: 'Free',
      freeLabel: 'For admissions offices',
      features: ['Instant certificate verification', 'No account required', 'API available', 'Tamper-evident seal validation'],
    },
    cta: 'Get started',
    ctaHref: '/signup',
  },
  terms: {
    title: 'Terms of Service',
    subtitle: 'Last updated: March 2026',
    intro: 'By using Doculet, you agree to these terms. Please read them carefully.',
    sections: [
      { heading: '1. Service', body: 'Doculet provides proof-of-funds verification services. We verify identity, bank balances, and sponsor commitments, and issue cryptographically sealed certificates for use by students and admissions offices.' },
      { heading: '2. Eligibility', body: 'You must be at least 18 years old and legally able to enter into binding contracts to use our services. Students, sponsors, and university staff must provide accurate information.' },
      { heading: '3. Data and privacy', body: 'Our handling of personal data is governed by our Privacy Policy and NDPR compliance. We never store your bank passwords.' },
      { heading: '4. Certificate validity', body: 'Certificates are time-bounded. The expiry date is displayed on each certificate. Verification of expired certificates will show invalid status.' },
      { heading: '5. Contact', body: 'Questions about these terms? Contact us at support@doculet.ai.' },
    ],
  },
  privacy: {
    title: 'Privacy Policy',
    subtitle: 'Last updated: March 2026',
    intro: 'Doculet Technologies Ltd. is committed to protecting your privacy in accordance with NDPR and applicable laws.',
    sections: [
      { heading: '1. Data we collect', body: 'We collect information you provide (email, name, identity documents) and verification data from our providers (Dojah for identity, Mono for bank verification). We do not store bank passwords.' },
      { heading: '2. How we use data', body: 'We use your data to verify your identity and bank balance, issue certificates, and improve our services. We share certificate verification data only when you share your certificate link.' },
      { heading: '3. Data retention', body: 'We retain verification records as required for audit and regulatory compliance. You may request deletion of your account and associated data.' },
      { heading: '4. Security', body: 'Data is encrypted in transit and at rest. Access to production data is restricted and logged.' },
      { heading: '5. Your rights', body: 'Under NDPR, you have the right to access, correct, and request deletion of your personal data. Contact privacy@doculet.ai.' },
    ],
  },
  contact: {
    title: 'Contact',
    subtitle: 'We are here to help.',
    email: 'support@doculet.ai',
    address: 'Victoria Island, Lagos, Nigeria',
    form: {
      nameLabel: 'Name',
      emailLabel: 'Email',
      messageLabel: 'Message',
      submitLabel: 'Send message',
    },
    note: 'For certificate verification issues or university access, email support@doculet.ai. Response within 24–48 hours.',
  },
  certificate: {
    title: 'Certificate Verification',
    verified: 'Doculet Seal — Verified',
    invalid: 'Invalid or expired',
    notFound: 'Certificate not found',
    holder: 'Holder',
    institution: 'Institution',
    amount: 'Verified balance',
    issued: 'Issued',
    expires: 'Expires',
    source: 'Source',
    tier: 'Tier',
    verifyAnother: 'Verify another certificate',
  },
  invite: {
    title: 'Sponsorship invite',
    fromLabel: 'From',
    schoolLabel: 'School',
    messageLabel: 'Message',
    acceptCta: 'Accept invite',
    declineCta: 'Decline',
    signInPrompt: 'Sign in to respond',
    signInCta: 'Sign in',
  },
  join: {
    title: 'Join Doculet',
    subtitle: 'Partner program signup',
    earlyAccess: 'We\'re onboarding select partners to grow the Doculet network. Email partners@doculet.ai to apply.',
  },
} as const;
