/** Marketing and public page copy — about, pricing, terms, privacy, contact */
import { routes } from '@/config/routes';

export const marketingCopy = {
  about: {
    title: 'About Doculet',
    subtitle: 'Connecting Nigerian students, sponsors, and US universities with verified proof-of-funds.',
    mission: {
      title: 'Our mission',
      body: 'Every year, thousands of Nigerian students lose their US university spots — not because the money is not there, but because bank statements alone are not trusted. Doculet verifies identity, bank balances, and sponsor commitments, then issues a cryptographically sealed certificate that admissions offices can verify in one click.',
    },
    values: [
      { title: 'Trust', body: 'We verify at source. BVN, live bank APIs, and sponsor attestation — not PDFs.' },
      { title: 'Privacy', body: 'NDPR compliant. No passwords stored. You control what is shared.' },
      { title: 'Speed', body: 'Fast, structured verification. Connect your bank for an instant result, or upload a statement for admin review.' },
    ],
    cta: 'Get your certificate',
    ctaHref: routes.auth.signup,
  },
  pricing: {
    title: 'Pricing',
    subtitle: 'Simple, transparent pricing for students and institutions.',
    student: {
      title: 'Students',
      audience: 'Nigerian students proving proof of funds for international study.',
      certFee: '₦80,000',
      certFeeLabel: 'Per certificate',
      renewalLabel: 'Renewal',
      renewalFee: '₦40,000',
      accountNote: 'Free to create an account.',
      features: [
        'Identity verification (BVN/NIN)',
        'Bank connection or PDF upload',
        'Sponsor invitation (Tier 3)',
        'Doculet Seal certificate',
        'Share link for universities',
      ] as const,
      cta: 'Get started',
      ctaHref: routes.auth.signup,
    },
    sponsor: {
      title: 'Sponsors',
      audience: 'Parents, family members, and companies funding student education.',
      free: 'Free',
      freeLabel: 'No fees for sponsors',
      features: [
        'Commit funds to student applications',
        'Identity verification included',
        'Track commitment status',
        'Multiple students supported',
      ] as const,
      cta: 'Create account',
      ctaHref: routes.auth.signup,
    },
    university: {
      title: 'Universities',
      audience: 'Admissions offices processing international student applications.',
      free: 'Contact us',
      freeLabel: 'Institutional access',
      features: [
        'Instant certificate verification',
        'Bulk roster management',
        'API integration available',
        'Tamper-evident seal validation',
      ] as const,
      cta: 'Contact us',
      ctaHref: routes.marketing.contact,
    },
    agent: {
      title: 'Agents',
      audience: 'Education consultants helping students through the process.',
      free: 'Commission-based',
      freeLabel: 'No upfront cost',
      features: [
        'Refer students to Doculet',
        'Track student progress',
        'Earn on successful certifications',
        'Dedicated agent dashboard',
      ] as const,
      cta: 'Get started',
      ctaHref: routes.auth.signup,
    },
    partner: {
      title: 'Partners',
      audience: 'Institutions embedding Doculet verification in their platform.',
      free: 'Custom',
      freeLabel: 'API access via arrangement',
      features: [
        'White-label integration',
        'REST API with webhooks',
        'Usage analytics dashboard',
        'Dedicated support',
      ] as const,
      contactHref: routes.marketing.contact,
      contactLabel: 'Contact sales',
      cta: 'Contact us',
      ctaHref: routes.marketing.contact,
    },
    cta: 'Begin now',
    ctaHref: routes.auth.signup,
    faqNote: 'Questions about pricing? Email us at',
    faqEmail: 'support@doculet.ai',
  },
  terms: {
    title: 'Terms of Service',
    subtitle: 'Last updated: March 2026',
    intro: 'By using Doculet, you agree to these terms. Please read them carefully.',
    sections: [
      { heading: '1. Service', body: 'Doculet provides proof-of-funds verification services for international education. We verify identity via BVN/NIN, bank balances via licensed APIs and document upload, and sponsor commitments via attestation. We issue cryptographically sealed certificates for use by students and admissions offices.' },
      { heading: '2. Eligibility', body: 'You must be at least 18 years old and legally able to enter into binding contracts to use our services. Students, sponsors, and university staff must provide accurate information. Providing false or misleading information may result in account suspension and certificate revocation.' },
      { heading: '3. Payment terms', body: 'Certificate issuance requires payment of the applicable fee via Paystack. Fees are non-refundable once a certificate has been issued. Renewal fees apply for certificates that have expired. All amounts are denominated in Nigerian Naira (NGN).' },
      { heading: '4. Certificate validity', body: 'Certificates are time-bounded. The expiry date is displayed on each certificate. Verification of expired certificates will show invalid status. Doculet reserves the right to revoke a certificate if the underlying verification data is found to be fraudulent.' },
      { heading: '5. Data and privacy', body: 'Our handling of personal data is governed by our Privacy Policy and the Nigeria Data Protection Regulation (NDPR). We never store your bank passwords. Bank verification is performed via licensed third-party APIs (Mono) or encrypted document upload with OCR.' },
      { heading: '6. Intellectual property', body: 'The Doculet Seal, certificate format, verification system, and all associated branding are the intellectual property of Doculet Technologies Ltd. You may share your certificate via the provided sharing mechanisms but may not alter, reproduce, or forge any certificate.' },
      { heading: '7. Limitation of liability', body: 'Doculet verifies information to the best of its ability using licensed data providers. We do not guarantee university admission outcomes. Our liability is limited to the fees paid for the specific certificate in question.' },
      { heading: '8. Governing law', body: 'These terms are governed by the laws of the Federal Republic of Nigeria. Any disputes shall be resolved in the courts of Lagos State.' },
      { heading: '9. Contact', body: 'Questions about these terms? Contact us at support@doculet.ai.' },
    ],
  },
  privacy: {
    title: 'Privacy Policy',
    subtitle: 'Last updated: March 2026',
    intro: 'Doculet Technologies Ltd. is committed to protecting your privacy in accordance with the Nigeria Data Protection Regulation (NDPR) and applicable laws.',
    sections: [
      { heading: '1. Data controller', body: 'Doculet Technologies Ltd., registered in Nigeria (CAC), is the data controller for all personal information processed through our platform. Our Data Protection Officer can be reached at privacy@doculet.ai.' },
      { heading: '2. Data we collect', body: 'We collect information you provide directly (name, email, phone number, identity documents) and verification data from licensed third-party providers: Dojah (BVN/NIN identity verification), Mono (bank account verification), and Paystack (payment processing). We do not store bank passwords or full bank transaction histories.' },
      { heading: '3. Legal basis for processing', body: 'We process your data on the basis of: (a) your consent when you create an account, (b) contractual necessity to provide verification services, and (c) legitimate interest in fraud prevention and platform security.' },
      { heading: '4. How we use data', body: 'We use your data to: verify your identity and bank balance, issue cryptographically sealed certificates, process payments, prevent fraud, communicate service updates, and improve our platform. We share certificate verification data only when you share your certificate link.' },
      { heading: '5. Data sharing', body: 'We share data only with: our licensed verification providers (Dojah, Mono, Paystack) for the purpose of verification and payment processing, and with admissions offices when you share your certificate link. We do not sell personal data.' },
      { heading: '6. Data retention', body: 'We retain verification records for 7 years as required for audit and regulatory compliance. Certificate data is retained for the certificate validity period plus 2 years. You may request deletion of your account and non-regulatory personal data at any time.' },
      { heading: '7. Security', body: 'Data is encrypted in transit (TLS 1.3) and at rest (AES-256). Access to production data is restricted by role and logged. We conduct regular security assessments. Supabase provides our authentication and storage infrastructure with SOC 2 Type II compliance.' },
      { heading: '8. Your rights under NDPR', body: 'You have the right to: access your personal data, correct inaccurate data, request deletion of your data (subject to regulatory retention requirements), object to processing, and data portability. To exercise these rights, contact privacy@doculet.ai. We will respond within 30 days.' },
      { heading: '9. Cookies', body: 'We use essential cookies for authentication and session management. We do not use advertising or tracking cookies. No third-party analytics cookies are loaded without your consent.' },
      { heading: '10. Changes', body: 'We may update this policy to reflect changes in our practices or applicable law. Material changes will be communicated via email to registered users.' },
    ],
  },
  contact: {
    title: 'Contact',
    subtitle: 'We are here to help.',
    email: 'support@doculet.ai',
    address: 'Victoria Island, Lagos, Nigeria',
    form: {
      nameLabel: 'Name',
      emailLabel: 'Email',
      messageLabel: 'Message',
      submitLabel: 'Send message',
    },
    note: 'For certificate verification issues or university access, email support@doculet.ai. We will be in touch.',
  },
  certificate: {
    title: 'Certificate Verification',
    verified: 'Doculet Seal — Verified',
    invalid: 'Invalid or expired',
    notFound: 'Certificate not found',
    lookupDescription: 'Enter the certificate token to validate the Doculet seal.',
    lookupPlaceholder: 'Certificate token',
    lookupCta: 'Verify certificate',
    metaDescription: 'Verify a Doculet proof-of-funds certificate.',
    certId: 'Certificate ID',
    status: 'Status',
    holder: 'Holder',
    institution: 'Institution',
    program: 'Programme',
    amount: 'Verified balance',
    issued: 'Issued',
    expires: 'Expires',
    source: 'Source',
    tier: 'Tier',
    tierLabel: (n: number) => `Tier ${n}`,
    downloadPdf: 'Download PDF',
    verifyAnother: 'Verify another certificate',
  },
  invite: {
    title: 'Sponsorship invite',
    fromLabel: 'From',
    schoolLabel: 'School',
    messageLabel: 'Message',
    acceptCta: 'Accept invite',
    declineCta: 'Decline',
    signInPrompt: 'Sign in to respond',
    signInCta: 'Sign in',
    createAccountCta: 'Create account',
    defaultDescription: 'A student has invited you to sponsor their proof-of-funds verification. Sign in to view details and respond.',
    studentDescription: (email: string, school: string | null) =>
      `A student (${email}) has invited you to sponsor their proof-of-funds verification.${school ? ` They are applying to ${school}.` : ''}`,
  },
  join: {
    title: 'Join Doculet',
    subtitle: 'Partner program signup',
    earlyAccess: 'We\'re onboarding select partners to grow the Doculet network. Email partners@doculet.ai to apply.',
  },
} as const;
