import { routes } from '@/config/routes';
import { commonErrors } from "./shared";
import { studentOnboardingCopy } from "./student-onboarding.copy";

export const studentCopy = {
  ...studentOnboardingCopy,

  firstSession: {
    eyebrow: 'GET STARTED',
    heading: 'Begin your application',
    description:
      'Complete your profile, verify your identity, and upload your documents to receive your proof of funds certificate.',
    cta: 'Begin your application',
    href: routes.dashboard.student.setup,
  },

  schools: {
    title: "Schools",
    subtitle: "Search universities across the United States and Nigeria. Select your program to set your funding target.",
    searchHint: "Search by university, city, or state\u2026",
    empty: {
      title: "No programs found",
      description: "No matching schools. Check the spelling or contact support to add your institution.",
      cta: "Clear filters",
    },
    card: {
      apply: "Apply",
      viewDetails: "View details",
      visitWebsite: "Visit website",
      estimatedTuition: "Estimated annual tuition (out-of-state)",
      durationMonths: "months",
      programSingular: "program",
      programPlural: "programs",
      noPrograms: "No programs listed yet.",
      morePrograms: "more",
    },
    feedback: {
      programSelected: "Program selected. Your funding target has been updated.",
      programError: "Unable to select this program. Please try again.",
    },
    filters: {
      allCountries: "All countries",
      unitedStates: "United States",
      nigeria: "Nigeria",
      stateLabel: "State",
      statePlaceholder: "All states",
    },
    institutionTypes: {
      public: "Public",
      private_nonprofit: "Private non-profit",
      private_forprofit: "Private for-profit",
    },
    loadMore: "Show more schools",
  },

  // Note: This section is retained because ManualKycReviewCard and verification
  // components still import from studentCopy.verify (kycFailure, bankSection, etc.).
  // The verification page uses src/config/copy/student-verification.copy.ts for
  // its page-level copy. The title/subtitle here are no longer used as page headers.
  verify: {
    title: "Identity verification",
    subtitle: "Confirm your identity so your certificate can be issued.",
    tracker: {
      title: "Verification progress",
      subtitle: "Each completed step brings you closer to your certificate.",
      completionLabel: "Completion",
      lastUpdatedLabel: "Last update",
    },
    status: {
      not_started: "Not started",
      pending: "Under review",
      verified: "Verified",
      failed: "Failed",
    },
    kycSection: {
      title: "Identity verification",
      tiers: [
        {
          label: "Contact details",
          description: "Confirm your email and phone number so we can keep you informed.",
        },
        {
          label: "Identity check",
          description: "Enter your BVN or NIN. This is verified with the Central Bank of Nigeria.",
        },
        {
          label: "Document verification",
          description: "Upload your passport and complete a selfie check for embassy-level confirmation.",
        },
      ],
      dojahForm: {
        title: "Verify your identity",
        description: "Enter your BVN, NIN, or passport number for a secure identity check.",
        tierLabel: "Tier",
        identityTypeLabel: "Identity type",
        identityNumberLabel: "Identity number",
        submitCta: "Submit identity check",
        pendingReferenceLabel: "Verification reference",
        tierOptions: {
          tier2: "Tier 2",
          tier3: "Tier 3",
        },
      },
      identityTypes: {
        bvn: "BVN",
        nin: "NIN",
        passport: "Passport",
      },
    },
    kycFailure: {
      firstAttempt: "Identity check did not match. Enter your name exactly as it appears on your BVN registration.",
      secondAttempt: "Automated verification was unsuccessful. Upload your government-issued ID and a selfie for manual review.",
      manualReviewTitle: "Upload ID for manual review",
      manualReviewDescription: "Upload a clear photo of your government-issued ID (passport, driver's licence, or national ID card) and a selfie holding the ID.",
      governmentIdLabel: "Government-issued ID",
      selfieLabel: "Selfie holding your ID",
      fileTooLarge: "File must be 8 MB or less.",
      governmentIdPlaceholder: "Select your government ID",
      selfiePlaceholder: "Take or select a selfie",
      uploadError: "Unable to upload files. Please try again.",
      submitCta: "Submit for manual review",
      submittingCta: "Submitting...",
      submittedFeedback: "Your documents have been submitted for manual review. We will be in touch once the review is complete.",
      submittedTitle: "Manual review in progress",
      submittedDescription: "Our team is reviewing your uploaded ID. You will be notified when the review is complete.",
    },
    bankExpiringBanner: "Your bank connection is about to expire. Reconnect to keep your balance verified.",
    bankSection: {
      title: "Bank verification",
      description:
        "Link your bank account so we can confirm your balance. Your credentials are protected by bank-grade encryption \u2014 we verify your balance, we never store your password.",
      connectCta: "Connect bank account",
      monoForm: {
        monoAccountIdLabel: "Mono account ID",
        bankNameLabel: "Bank name",
        accountNumberLabel: "Account number",
        submitCta: "Save connection",
      },
      connectedLabel: "Connected account",
      uploadAlternativeCta: "Upload a bank statement instead",
      orDivider: "or",
      connectMonoCta: "Connect your bank account",
      monoWidgetLoading: "Opening bank connection...",
      monoWidgetError: "Unable to open the bank connection widget. Please try again.",
      manualForm: {
        title: "Add bank account manually",
        description: "For banks not supported by Mono, or accounts outside Nigeria.",
        bankNameLabel: "Bank name",
        accountNumberLabel: "Account number (NUBAN or IBAN)",
        currencyLabel: "Account currency",
        accountTypeLabel: "Account type",
        countryLabel: "Country code (e.g. NG, GB, US)",
        submitCta: "Add account",
        successToast: "Bank account added. Upload a statement to complete verification.",
      },
      accountsList: {
        title: "Your bank accounts",
        empty: "No bank accounts linked yet.",
        monoVerified: "Verified via Mono",
        manualUpload: "Manually added",
        removeCta: "Remove",
        removeConfirmTitle: "Remove this bank account?",
        removeConfirmDescription: "This action cannot be undone. You may need to re-link this account later.",
        removeConfirmCta: "Remove account",
        removeCancel: "Cancel",
        removeSuccess: "Bank account removed.",
      },
    },
    actions: {
      refresh: "Refresh status",
    },
    feedback: {
      dojahStarted: "Identity check submitted. Your status will update once verification is complete.",
      monoConnected: "Bank connection saved. Your verification progress has been updated.",
      manualAdded: "Bank account added. Upload a bank statement to complete verification.",
      loadError: "Unable to load verification status.",
      dojahError: "Unable to start identity verification. Please try again.",
      monoError: "Unable to save your bank connection.",
    },
  },

  documents: {
    title: "Documents",
    subtitle: "Upload your bank statement to verify your funds.",
    uploadCta: "Upload document",
    typeOptions: [
      { value: "bank_statement", label: "Bank statement" },
    ],
    types: {
      bankStatement: "Bank statement",
    },
    status: {
      pending: "Under review",
      approved: "Approved",
      rejected: "Rejected",
      moreInfoRequested: "More information needed",
      expired: "Expired",
    },
    upload: {
      title: "Upload your bank statement",
      description: "PDF, PNG, or JPG. Maximum 8 MB. Make sure your name and current balance are clearly visible.",
      documentTypeLabel: "Document type",
      documentTypeHint: "Choose the document type",
      fileLabel: "Document file",
      fileHelp: "Your file is encrypted and reviewed by the Doculet verification team. We accept recent statements (6 months or less).",
      selectedFileLabel: "Selected file",
      fileAccept: "application/pdf,image/png,image/jpeg",
      submitIdle: "Upload document",
      submitUploading: "Uploading...",
      submitSuccessMessage: "Document submitted. You will be notified when the review is complete.",
      dropzoneLabel: "Drag and drop your file, or",
      dropzoneBrowse: "browse",
      selectedFileChangeHint: "\u2014 click to change",
    },
    reuploadCta: "Resubmit with correction",
    list: {
      title: "Submitted documents",
      description: "Track review decisions and respond to feedback.",
      ariaLabel: "Submitted document list",
      submittedAtLabel: "Submitted",
      rejectionReasonLabel: "Reason",
      rejectionReasonFallback: "No rejection reason provided.",
      viewCta: "View",
      reuploadReplacementCta: "Upload a replacement",
      moreInfoNoteLabel: "More information requested",
      moreInfoResubmitCta: "Resubmit with the requested information",
    },
    states: {
      loadingTitle: "Loading your documents",
      loadingDescription: "Retrieving your latest document status.",
      errorTitle: "Unable to load documents",
      errorDescription: "Please try again. If this continues, contact support.",
      retryCta: "Retry",
      emptyTitle: "No documents yet",
      emptyDescription:
        "Upload your bank statement to verify your funds.",
    },
    validation: {
      documentTypeRequired: "Select a document type.",
      fileRequired: "Choose a file before uploading.",
      fileTypeInvalid: "Upload a PDF, PNG, or JPG file.",
      fileTooLarge: "File size must be 8 MB or less.",
      uploadFailed: "Document upload failed. Please check your file and try again.",
    },
    empty: {
      title: "No documents yet",
      description:
        "Upload your bank statement to verify your funds.",
    },
    allApproved: {
      heading: "All documents approved",
      body: "Your supporting documents have been verified. Your proof of funds is ready to review.",
      cta: "View your proof status",
    },
  },

  phoneVerificationPrompt: {
    eyebrow: 'NEXT STEP',
    heading: 'Verify your phone number',
    description: 'Confirm your phone number to unlock identity verification.',
    cta: 'Verify now',
  },

  phoneSheet: {
    title: 'Confirm your phone number',
    description: 'We need your phone number to complete your identity profile. You will receive a one-time code.',
    phonePlaceholder: '+234 800 000 0000',
    phoneLabel: 'Phone number',
    sendCodeCta: 'Send code',
    otpLabel: 'Verification code',
    otpPlaceholder: '_ _ _ _ _ _',
    confirmCta: 'Confirm',
    confirmingCta: 'Confirming...',
    sendingCta: 'Sending...',
    successMessage: 'Phone number confirmed.',
    errorSend: 'Unable to send the code. Check your number and try again.',
    errorVerify: 'Code did not match. Please try again.',
  },

  kycSheet: {
    title: 'Verify your identity',
    description: 'Enter your BVN or NIN for a secure identity check. This information is never stored by Doculet.',
    identityTypeLabel: 'Identity type',
    identityNumberLabel: 'Identity number',
    identityTypes: {
      bvn: 'BVN \u2014 Bank Verification Number',
      nin: 'NIN \u2014 National Identification Number',
      passport: 'International Passport',
    },
    submitCta: 'Submit check',
    submittingCta: 'Checking...',
    successMessage: 'Identity check submitted. Your status will update once verification is complete.',
    errorGeneric: 'Identity check failed. Check your number and try again.',
    failureGuidance: 'The number did not match. Enter your name exactly as it appears on your BVN or NIN registration.',
    manualFallbackCta: 'Upload your ID instead',
    manualFallbackHref: routes.dashboard.student.documents,
  },

  bankVerification: {
    sectionTitle: 'Bank verification',
    notVerifiedDescription: 'Connect your bank account or upload a recent statement to confirm your balance.',
    monoConnectCta: 'Connect your bank account',
    monoConnectDescription: 'Secure real-time connection. Your login credentials are never stored.',
    orDivider: 'or',
    statementUploadLabel: 'Upload a bank statement',
    statementUploadHint: 'PDF or image, 6 months or less, maximum 8 MB.',
    status: {
      verified: 'Verified',
      pendingReview: 'Statement under review',
      notVerified: 'Not verified',
      rejected: 'Rejected',
    },
    rejection: {
      prefix: 'Bank statement rejected',
      resubmitCta: 'Upload a new statement',
    },
    connectedBank: '{bankName} (****{last4})',
    errorConnect: 'Unable to connect bank account. Please try again.',
    errorWidget: 'Unable to load the bank connection widget.',
    loadingCta: 'Connecting...',
    monoFailed: {
      heading: 'Bank connection failed',
      descriptionFallback: 'We could not verify your bank balance. Try connecting again or upload a bank statement.',
      retryCta: 'Try again',
      uploadCta: 'Upload a bank statement',
    },
  },

  ocrCard: {
    title: 'Statement submitted',
    submittedLabel: 'Review the extracted details and confirm before submitting.',
    fieldLabels: {
      accountHolder: 'Account holder',
      balance: 'Balance',
      dateRange: 'Statement period',
    },
    previewCta: 'Preview',
    ocrFailedHeading: 'Automatic statement scan failed',
    ocrFailedFallback: 'Your document is still queued for manual review.',
    ocrInProgressHeading: 'Statement analysis in progress',
    ocrInProgressFallback: 'Analyzing your bank statement',
    confidenceLabel: (pct: number) => `${Math.round(pct * 100)}% match confidence`,
    ocrConfirm: 'Confirm and submit',
    ocrCancel: 'Cancel \u2014 re-upload',
    ocrManualNote: 'We could not read this document automatically.',
    ocrCancelling: 'Cancelling\u2026',
    manualFields: {
      namePlaceholder: 'Account holder name',
      nameLabel: 'Account holder name',
      accountNumberPlaceholder: 'Account number',
      accountNumberLabel: 'Account number',
      bankNamePlaceholder: 'Bank name',
      bankNameLabel: 'Bank name',
      balancePlaceholder: 'Balance (e.g. 1500000)',
      balanceLabel: 'Balance (NGN)',
    },
  },

  proof: {
    title: "Proof of funds",
    subtitle: "Complete each step below to receive your verified proof-of-funds certificate.",
    progress: {
      title: "Verification checklist",
      description: "Your certificate is issued when all steps are complete.",
      progressLabel: "{completed} of {total} complete",
      completeBadge: "Complete",
      pendingBadge: "Pending",
      items: {
        school: {
          label: "School and program",
          completeDetail: "School and program confirmed.",
          pendingDetail: "Select your school and program.",
          pendingHref: routes.dashboard.student.schools,
        },
        kyc: {
          label: "Identity verification",
          completeDetail: "Identity verified.",
          pendingDetail: "Confirm your identity to continue.",
          pendingHref: routes.dashboard.student.verification,
        },
        bank: {
          label: "Bank verification",
          completeDetail: "Bank account linked and verified.",
          pendingDetail: "Link your bank account or upload a statement.",
          pendingHref: routes.dashboard.student.documentsBank,
        },
        sponsor: {
          label: "Sponsor commitment",
          completeDetail: "Sponsor has an active commitment.",
          pendingDetail: "Invite and confirm at least one sponsor.",
          pendingHref: routes.dashboard.student.sponsors,
        },
        documents: {
          label: "Supporting documents",
          completeDetail: "At least one document has been approved.",
          pendingDetail: "Upload documents for review.",
          pendingHref: routes.dashboard.student.documents,
        },
      },
    },
    certificate: {
      title: "Verified certificate",
      description:
        "Your certificate is secured and cannot be altered or forged. Any embassy or university can verify it using the link below.",
      issuedBadge: "Issued",
      lockedBadge: "Locked",
      idLabel: "Certificate ID",
      issuedAtLabel: "Issued",
      shareLinkLabel: "Secure share link",
      noShareLink: "No share link generated yet.",
      generateShareCta: "Generate secure share link",
      regenerateShareCta: "Regenerate share link",
      generatingCta: "Generating link...",
      copyLinkCta: "Copy link",
      copiedLinkCta: "Copied",
      trustTitle: "Trust signals",
      unavailableValue: "Unavailable",
      trust: {
        sponsorCountLabel: "Verified sponsors",
        committedAmountLabel: "Committed amount",
        approvedDocumentsLabel: "Approved documents",
        pendingDocumentsLabel: "Pending documents",
        lastAuditLabel: "Last audit update",
      },
    },
    payment: {
      title: "Certificate issuance fee",
      description: "A one-time fee is required to issue your tamper-evident proof-of-funds certificate.",
      renewalDescription: "A renewal fee is required to re-issue your proof-of-funds certificate.",
      amountLabel: "Fee",
      firstIssueFee: "80,000",
      renewalFee: "40,000",
      currency: "NGN",
      payCta: "Pay certificate fee",
      payingCta: "Processing payment...",
      successMessage: "Payment confirmed. Your certificate is now active.",
      errorMessage: "Payment could not be verified. Please try again or contact support.",
      alreadyPaid: "Certificate fee paid",
      paidAtLabel: "Paid on",
      waived: "Fee waived",
    },
    locked: {
      title: "Certificate not yet available",
      description:
        "Complete identity verification, bank verification, documents, and sponsor confirmation to receive your certificate.",
      helper: "Complete all checklist items to activate sharing.",
    },
    empty: {
      title: "Your proof checklist",
      description:
        "Complete identity verification, link your bank account, and confirm a sponsor to receive your certificate.",
      cta: "Continue verification",
      illustrationLabel: "Shield and document checklist illustration",
    },
    underFinalReview: {
      heading: 'Under final review',
      desc: 'Your proof of funds package is complete. We are preparing your certificate.',
    },
    states: {
      loadingTitle: "Loading certificate",
      loadingDescription: "Fetching your latest verification and audit records.",
      errorTitle: "Unable to load certificate",
      errorDescription: "Please refresh to try again.",
      shareError: "Unable to generate a share link. Please try again.",
      retryCta: "Try again",
      shareWithUniversity: {
        heading: "Share with your university",
        body: "Your certificate is ready. Send the secure link to your admissions office to confirm your proof of funds.",
        cta: "Copy share link",
      },
    },
    share: {
      sectionTitle: "Share your certificate",
      whatsappCta: "Share via WhatsApp",
      whatsappMessage: "Here is my Doculet proof-of-funds certificate. Verify it here: {url}",
      emailCta: "Send via email",
      emailSubject: "Doculet Proof of Funds Certificate",
      emailBody: "Please find my verified proof-of-funds certificate. You can verify its authenticity at: {url}",
      downloadCta: "Download PDF",
      downloadingCta: "Preparing PDF...",
      copyLinkCta: "Copy verification link",
      copiedLinkCta: "Link copied",
      trackingNote: "Each share is logged for your records.",
      shareCta: "Share",
    },
    certSharing: {
      title: "Share your certificate",
      whatsapp: "Share via WhatsApp",
      copyLink: "Copy verification link",
      copied: "Copied!",
      downloadPdf: "Download PDF",
      sendToInstitution: "Send to institution",
      verificationLinkLabel: "Anyone with this link can verify your certificate.",
      institutionEmailLabel: "Institution email address",
      institutionEmailPlaceholder: "admissions@university.edu",
      sendCta: "Send",
      sendingCta: "Sending...",
      sendSuccess: "Certificate sent to {email}.",
      sendError: "Unable to send. Please try again.",
    },
  },

  sponsorInvite: {
    title: "Invite a sponsor",
    subtitle:
      "A sponsor commits funds toward your education. Once they verify, their contribution counts toward your certificate.",
    inviteByEmail: {
      label: "Sponsor's email address",
      inputHint: "Enter your sponsor's email address",
      sendCta: "Send invitation",
    },
    status: {
      pending: "Invitation sent \u2014 awaiting response",
      accepted: "Accepted \u2014 sponsor completing verification",
      declined: "Invitation declined",
      cancelled: "Invitation cancelled",
    },
    cancel: "Cancel invitation",
    sendingCta: "Sending...",
    errorMessage: "Unable to send the invitation. Please try again.",
  },

  sponsorCommitted: {
    title: 'Sponsor committed',
    amountLabel: 'Committed amount',
    typeLabel: 'Funding type',
  },

  sponsorWithdrawn: {
    title: 'Sponsor withdrew commitment',
    desc: 'has withdrawn their commitment. Update your funding type to continue.',
    cta: 'Update funding type',
  },

  nextSteps: {
    postOnboarding: {
      title: "Profile created",
      body: "Your funding profile is active. Next, verify your identity to move closer to your certificate.",
      cta: "Continue to verification",
      href: routes.dashboard.student.verification,
    },
    postKyc: {
      title: "Identity verified",
      body: "Your identity is confirmed. Connect your bank account so we can verify your funds.",
      cta: "Connect bank account",
      href: routes.dashboard.student.documentsBank,
    },
    postBank: {
      title: "Bank verified",
      body: "Your bank account is linked. Upload your supporting documents next.",
      cta: "Upload documents",
      href: routes.dashboard.student.documents,
    },
    postDocs: {
      title: "Documents approved",
      body: "All documents have been approved. Invite a sponsor or check your certificate status.",
      cta: "View proof status",
      href: routes.dashboard.student.proof,
    },
    postSponsor: {
      title: "Sponsor confirmed",
      body: "Your sponsor has committed funds. Your proof certificate is being prepared.",
      cta: "View certificate",
      href: routes.dashboard.student.proof,
    },
    postCertificate: {
      title: "Certificate issued",
      body: "Your proof-of-funds certificate is ready. Download or share it with your university.",
      cta: "View certificate",
      href: routes.dashboard.student.proof,
    },
  },

  currency: {
    dualDisplayLabel: "NGN equivalent",
    coverageLabel: "Tuition coverage",
    coverageValue: "{percent}% covered",
    rateDisclaimer: "Exchange rate from {source} as of {date}. Rates are indicative.",
    bufferRecommendation: "We recommend holding 10\u201315% above the current NGN equivalent to account for rate fluctuation.",
    staleRateWarning: "Exchange rate data is more than 24 hours old. Amounts may differ from current market rates.",
  },

  settings: {
    title: "Settings",
    subtitle: "Manage your personal details, password, and account security.",
    editProfile: {
      title: "Personal information",
      description: "Update your name, phone number, and WhatsApp.",
      fullNameLabel: "Full name",
      phoneLabel: "Phone number",
      whatsappLabel: "WhatsApp number",
      saveCta: "Save changes",
      savingCta: "Saving...",
      successFeedback: "Profile updated.",
      errorFeedback: "Unable to update profile. Please try again.",
    },
    changePassword: {
      title: "Change password",
      description: "Update your password without leaving the dashboard.",
      currentLabel: "Current password",
      newLabel: "New password",
      confirmLabel: "Confirm new password",
      changeCta: "Change password",
      changingCta: "Changing...",
      successFeedback: "Password updated.",
      errorFeedback: "Unable to change password. Please try again.",
      mismatchError: "Passwords do not match.",
    },
    changeSchool: {
      title: "School and program",
      description: "Update your selected school and program.",
      changeCta: "Change school",
      saveCta: "Save",
      savingCta: "Saving...",
      cancelCta: "Cancel",
      schoolLabel: "School",
      schoolPlaceholder: "Select school",
      programLabel: "Program",
      programPlaceholder: "Select program",
      noSchoolSelected: "No school selected",
    },
    sponsorInvites: {
      title: "Declined sponsors",
      description: "Re-invite sponsors who previously declined.",
      reinviteCta: "Re-invite",
    },
    changeFunding: {
      title: "Funding arrangement",
      description: "Change how your education is funded.",
      changeCta: "Change funding",
    },
    errors: {
      loadError: "Unable to load settings. Please try again.",
      tryAgain: "Try again",
    },
  },

  support: {
    title: "Support",
    subtitle: "Assistance with your funding verification.",
    empty: {
      title: "No support tickets",
      description: "Submit a ticket and our team will respond.",
    },
    createCta: "Create ticket",
    form: {
      subjectLabel: "Subject",
      subjectPlaceholder: "Brief description of your issue",
      messageLabel: "Message",
      messagePlaceholder: "Describe your question or issue in detail\u2026",
      submitCta: "Submit ticket",
      submittingCta: "Submitting\u2026",
    },
    feedback: {
      success: "Ticket submitted. We will be in touch.",
      error: "Unable to submit ticket. Please try again.",
    },
    ticket: {
      status: "Status",
      statusLabels: { open: "Open", in_progress: "In progress", resolved: "Resolved", closed: "Closed" },
      createdAt: "Submitted",
    },
  },

  nav: {
    overview: "Overview",
    schools: "Schools",
    verify: "Verification",
    documents: "Documents",
    proof: "Proof",
    invite: "Invite sponsor",
    breadcrumbs: {
      applicationSetup: "Application Setup",
      proofOfFunds: "Proof of Funds",
    },
  },

  blocked: {
    verification: {
      pageTitle: 'Verification',
      blockedTitle: 'Verification is locked',
      blockedReason: 'Complete your onboarding setup first.',
      ctaLabel: 'Go to setup',
      ctaHref: routes.dashboard.student.setup,
    },
    documents: {
      pageTitle: 'Documents',
      blockedTitle: 'Documents are locked',
      blockedReason: 'Complete your identity verification first.',
      ctaLabel: 'Go to verification',
      ctaHref: routes.dashboard.student.verification,
    },
    proof: {
      pageTitle: 'Proof of Funds',
      blockedTitle: 'Proof of Funds is locked',
      blockedReason: 'Complete verification and upload your required documents first.',
      ctaLabel: 'Go to documents',
      ctaHref: routes.dashboard.student.documents,
    },
  },

  errors: commonErrors,
} as const;

export type StudentCopy = typeof studentCopy;
