import { commonErrors } from "./shared";

export const universityCopy = {
  overview: {
    welcomeTitle: "University overview",
    title: "Overview",
    eyebrow: "Program and student management",
    subtitle: "Here's what needs your attention today.",
    stats: {
      programs: { label: "Programs", sub: "Active programs" },
      students: { label: "Students", sub: "Enrolled" },
      certsIssued: { label: "Certs issued", sub: "This cycle" },
      docsPending: { label: "Docs pending", sub: "Awaiting review" },
    },
    activePrograms: {
      heading: "Active programs",
      empty: "No programs configured yet.",
    },
    metrics: {
      pending: "Pending verifications",
      approvedToday: "Approved today",
      flagged: "Flagged items",
      totalStudents: "Total students",
    },
    activity: {
      sectionTitle: "Recent activity",
      emptyLabel: "No recent activity.",
      eventTitles: {
        pending: "Document submitted",
        approved: "Document approved",
        rejected: "Document rejected",
        more_info_requested: "More info requested",
        expired: "Document expired",
      } as Record<string, string>,
      documentTypes: {
        passport: "Passport",
        bank_statement: "Bank statement",
        offer_letter: "Offer letter",
        affidavit: "Affidavit",
        cac: "CAC document",
      } as Record<string, string>,
    },
    empty: {
      heading: "No verifications yet",
      body: "Student proof-of-funds submissions will appear here once they submit their documents.",
      action: "Review pipeline",
      actionHref: "/dashboard/university/pipeline",
    },
    error: {
      heading: "Failed to load overview",
      body: "We couldn't load the dashboard data. Please try again.",
      retry: "Retry",
    },
  },

  pipeline: {
    title: "Application pipeline",
    subtitle: "Process applications at scale. Verify in seconds.",
    filters: {
      status: "Status",
      program: "Program",
      dateRange: "Date range",
      search: "Search applicants…",
    },
    table: {
      applicant: "Applicant",
      program: "Program",
      status: "Status",
      submitted: "Submitted",
      lastUpdated: "Last updated",
      action: "Action",
      documents: "Documents",
      kycStatus: "KYC status",
    },
    kycLabels: {
      not_started: "Not started",
      pending: "Pending",
      verified: "Verified",
      failed: "Failed",
    },
    statusLabels: {
      submitted: "Submitted",
      underReview: "Under review",
      approved: "Approved",
      rejected: "Rejected",
      moreInfoRequested: "More info needed",
      waitlisted: "Waitlisted",
    },
    actions: {
      review: "Review",
      approve: "Approve",
      reject: "Reject",
      requestInfo: "Request info",
      exportCsv: "Export CSV",
      bulkApprove: "Approve selected",
    },
    empty: {
      title: "No applications yet",
      description:
        "Applications from students will appear here once they submit their proof of funds.",
    },
    stats: {
      total: "Total applications",
      pendingReview: "Pending review",
      approvedThisWeek: "Approved this week",
      averageProcessingTime: "Avg. processing time",
    },
    reviewDialog: {
      title: "Review application",
      notesLabel: "Reviewer notes",
      notesHint: "Share feedback or next steps with the applicant.",
      approveCta: "Approve",
      rejectCta: "Reject",
      requestInfoCta: "Request more info",
      cancel: "Cancel",
    },
  },

  verifyCert: {
    title: "Verify a certificate",
    subtitle:
      "Enter a certificate token or scan a QR code to instantly verify authenticity.",
    tokenInput: {
      label: "Certificate token",
      inputHint: "e.g. DOC-2025-A1B2C3D4",
      verifyCta: "Verify now",
    },
    qrScan: {
      label: "Scan QR code",
      description: "Point your camera at the QR code on the student's certificate.",
      startScan: "Open camera",
    },
    result: {
      valid: {
        title: "Certificate valid",
        description: "This certificate is authentic and has not been tampered with.",
        issuedTo: "Issued to",
        issuedOn: "Issued on",
        expiresOn: "Expires on",
        program: "Program",
        fundingVerified: "Funding verified",
      },
      expired: {
        title: "Certificate expired",
        description: "This certificate was valid but has since expired.",
      },
      revoked: {
        title: "Certificate revoked",
        description: "This certificate has been revoked and is no longer valid.",
      },
      notFound: {
        title: "Certificate not found",
        description:
          "No certificate matches this token. Check the reference and try again.",
      },
    },
    verifyAnother: "Verify another certificate",
  },

  students: {
    title: "Students",
    subtitle: "All students enrolled at your institution.",
    filterByProgram: "Filter by program",
    allPrograms: "All programs",
    exportCsv: "Export CSV",
    exporting: "Exporting\u2026",
    exportSuccess: "CSV downloaded.",
    table: {
      student: "Student",
      program: "Program",
      kycStatus: "KYC status",
      documents: "Documents",
      certificateId: "Certificate ID",
      enrolled: "Enrolled",
    },
    kycLabels: {
      not_started: "Not started",
      pending: "Pending",
      verified: "Verified",
      failed: "Failed",
    },
    empty: {
      title: "No students enrolled",
      description: "Students who apply to your institution will appear here.",
    },
    card: {
      enrolled: "Enrolled",
      documents: "documents",
      certificate: "Certificate",
    },
  },

  documents: {
    title: "Document queue",
    subtitle: "Review and approve student document submissions.",
    table: {
      student: "Student",
      type: "Document type",
      uploaded: "Uploaded",
      status: "Status",
      actions: "Actions",
    },
    typeLabels: {
      passport: "Passport",
      bank_statement: "Bank statement",
      offer_letter: "Offer letter",
      affidavit: "Affidavit",
      cac: "CAC document",
    },
    statusLabels: {
      pending: "Pending",
      approved: "Approved",
      rejected: "Rejected",
      more_info_requested: "More info needed",
      expired: "Expired",
    },
    actions: { view: "View", approve: "Approve", reject: "Reject", requestInfo: "Request info" },
    requestInfoReasonLabel: "What information is needed?",
    requestInfoReasonHint: "Describe what the student needs to provide or correct.",
    requestInfoConfirm: "Send request",
    rejectReasonLabel: "Reason for rejection",
    rejectReasonHint: "Briefly explain why this document was rejected.",
    rejectConfirm: "Confirm rejection",
    rejectCancel: "Cancel",
    bulkBar: {
      selected: "selected",
      clearSelection: "Clear selection",
      approve: "Approve all",
      reject: "Reject all",
      requestInfo: "Request info",
    },
    bulkSuccess: {
      approved: "Documents approved.",
      rejected: "Documents rejected.",
      more_info_requested: "Information requested from students.",
    },
    empty: {
      title: "No documents in queue",
      description: "Student document submissions will appear here for review.",
    },
  },

  queue: {
    title: 'Review queue',
    subtitle: 'Prioritized items awaiting your review.',
    table: {
      student: 'Student',
      documentType: 'Document type',
      submitted: 'Submitted',
      status: 'Status',
      actions: 'Actions',
    },
    statusLabels: {
      pending: 'Pending',
      approved: 'Approved',
      rejected: 'Rejected',
      more_info_requested: 'More info needed',
      expired: 'Expired',
    },
    actions: {
      approve: 'Approve',
      reject: 'Reject',
      viewDetails: 'View details',
    },
    empty: { title: 'Queue is empty', description: 'Items requiring review will appear here.' },
  },
  programs: {
    title: 'Programs',
    subtitle: 'Manage programs and proof-of-funds requirements.',
    table: {
      name: 'Program name',
      tuition: 'Proof target',
      duration: 'Duration',
      students: 'Students',
      status: 'Status',
      actions: 'Actions',
    },
    statusLabels: {
      active: 'Active',
      inactive: 'Inactive',
    },
    addProgram: 'Add program',
    addProgramDescription: 'Create a new program at your institution.',
    cancel: 'Cancel',
    form: {
      nameLabel: 'Program name',
      namePlaceholder: 'e.g. BSc Computer Science',
      nameError: 'Program name must be at least 2 characters.',
      tuitionLabel: 'Proof target amount (NGN)',
      tuitionPlaceholder: 'e.g. 2500000',
      tuitionError: 'Enter a valid amount greater than zero.',
      durationLabel: 'Duration (months)',
      durationPlaceholder: 'e.g. 48',
      descriptionLabel: 'Description (optional)',
      descriptionPlaceholder: 'Brief description of this program.',
      submitLabel: 'Create program',
      submittingLabel: 'Creating\u2026',
    },
    durationUnit: 'months',
    success: 'Program created.',
    error: 'Failed to create program. Try again.',
    empty: { title: 'No programs configured', description: 'Add programs to accept student applications.' },
    editDialog: {
      title: 'Edit program',
      description: 'Update program details.',
      saveCta: 'Save changes',
      saving: 'Saving\u2026',
      success: 'Program updated.',
    },
    deactivate: {
      cta: 'Deactivate',
      confirmTitle: 'Deactivate program',
      confirmDescription: (name: string) =>
        `Deactivate ${name}? Students in this program will not be affected.`,
      confirmCta: 'Deactivate',
      cancel: 'Cancel',
      success: 'Program deactivated.',
      error: 'Failed to deactivate program. Try again.',
    },
    exportStudents: {
      cta: 'Export students',
      description: 'Download a CSV of all students at your institution.',
      empty: 'No student data to export.',
    },
  },
  reports: {
    title: 'Reports',
    subtitle: 'Analytics and reporting.',
    metrics: {
      totalStudents: 'Total students',
      verifiedStudents: 'Verified students',
      pendingVerifications: 'Pending verifications',
      rejectedDocuments: 'Rejected documents',
      totalPrograms: 'Programs offered',
      approvalRate: 'Approval rate',
    },
    sections: {
      overview: 'Overview metrics',
      breakdown: 'Status breakdown',
    },
    empty: { title: 'No reports yet', description: 'Report data will appear here once students enrol.' },
  },
  team: {
    title: 'Team',
    subtitle: 'Staff management and permissions.',
    table: {
      name: 'Name',
      email: 'Email',
      role: 'Role',
      added: 'Added',
      actions: 'Actions',
    },
    addMember: 'Add team member',
    addMemberDescription: 'Invite a staff member to access your dashboard.',
    form: {
      nameLabel: 'Full name',
      namePlaceholder: 'e.g. Adebayo Johnson',
      emailLabel: 'Email address',
      emailPlaceholder: 'e.g. adebayo@university.edu.ng',
      roleLabel: 'Role',
      submitLabel: 'Add member',
      submittingLabel: 'Adding\u2026',
    },
    roleLabels: {
      admin: 'Admin',
      reviewer: 'Reviewer',
      viewer: 'Viewer',
    } as Record<string, string>,
    removeConfirmTitle: 'Remove team member',
    removeConfirmDescription: 'Are you sure you want to remove this member? This action cannot be undone.',
    removeConfirmAction: 'Remove',
    removeCancel: 'Cancel',
    success: 'Team member added.',
    removeSuccess: 'Team member removed.',
    error: 'Failed to update team. Please try again.',
    empty: { title: 'No team members', description: 'Add staff to help with verification.' },
  },
  import: {
    title: 'Bulk import',
    subtitle: 'Import students in bulk via email addresses.',
    instructions: 'Paste email addresses (one per line) or upload a CSV file with an "email" column.',
    textareaPlaceholder: 'student1@example.com\nstudent2@example.com',
    uploadLabel: 'Or upload CSV',
    previewTitle: 'Preview',
    previewDescription: 'Review the email addresses before sending invites.',
    emailCount: 'emails parsed',
    submitLabel: 'Send invites',
    submittingLabel: 'Sending\u2026',
    success: 'Invitations sent successfully.',
    error: 'Failed to send some invitations. Please try again.',
    invalidEmails: 'Some entries are not valid email addresses and were excluded.',
    empty: { title: 'Import students', description: 'Upload a CSV or paste emails to add multiple students at once.' },
  },

  settings: {
    title: "Settings",
    subtitle: "Manage your institution profile.",
    profile: {
      title: "Institution profile",
      organizationNameLabel: "Organisation name",
      schoolNameLabel: "Linked school",
      schoolNameHint: "Contact support to change your linked school.",
      saveLabel: "Save changes",
      savingLabel: "Saving\u2026",
      savedLabel: "Settings saved.",
      validation: {
        orgNameMin: "Organisation name must be at least 2 characters.",
        orgNameMax: "Organisation name must be at most 120 characters.",
      },
    },
    errors: {
      saveError: "Failed to save settings. Please try again.",
      loadError: "Unable to load settings. Please try again.",
      tryAgain: "Try again",
    },
  },

  journey: {
    stages: {
      receive_applications: 'Receive applications',
      review_documents: 'Review documents',
      monitor_pipeline: 'Monitor pipeline',
    },
    nextActions: {
      receive_applications: {
        label: 'Awaiting student submissions',
        description: 'Student proof-of-funds documents will appear here when submitted.',
        cta: 'View pipeline',
        href: '/dashboard/university/pipeline',
      },
      review_documents: {
        label: 'Review pending documents',
        description: 'Students have submitted documents that need your review.',
        cta: 'Open review queue',
        href: '/dashboard/university/documents',
      },
      monitor_pipeline: {
        label: 'Monitor application pipeline',
        description: 'All pending reviews are clear. Monitor the pipeline for new submissions.',
        cta: 'View pipeline',
        href: '/dashboard/university/pipeline',
      },
    },
    completionMessage: 'All document reviews are up to date.',
  },

  nav: {
    pipeline: "Pipeline",
    verify: "Verify certificate",
    settings: "Settings",
  },

  errors: commonErrors,
} as const;

export type UniversityCopy = typeof universityCopy;
