/** Auth / account / session primitives */

export const authPrimitives = {
  sessionManagement: {
    thisDevice: "This device",
    activeSession: "Active session",
    revokeSession: "Revoke session",
    revoke: "Revoke",
    noOtherSessions: "No other active sessions. You are signed in on this device only.",
    lastActive: "Last active",
    title: "Active Sessions",
    description: "Devices and browsers currently signed in to your account.",
    signOutAllOthers: "Sign out of all other sessions",
    loading: "Loading sessions…",
    revoked: "Session revoked.",
    revokeFailed: "Session revocation failed. Try again.",
    revokedAll: "All other sessions have been signed out.",
    browsers: {
      Chrome: "Google Chrome",
      Safari: "Safari",
      Firefox: "Mozilla Firefox",
      Edge: "Microsoft Edge",
      Opera: "Opera",
      Unknown: "Unknown browser",
    },
    devices: {
      desktop: "Desktop",
      mobile: "Mobile device",
      tablet: "Tablet",
      unknown: "Unknown device",
    },
  },
  sessionTimeout: {
    warningTitle: "Your session is about to expire",
    warningBody: "You will be signed out due to inactivity. Stay signed in to continue.",
    signOut: "Sign out",
    staySignedIn: "Stay signed in",
  },
  accountClosure: {
    title: "Close account",
    description: "Permanently deactivate your account. This action cannot be undone.",
    button: "Close account",
    confirmTitle: "Are you sure?",
    confirmBody: "Your account and all associated data will be deactivated immediately. This cannot be reversed.",
    confirmButton: "Yes, close account",
    cancel: "Cancel",
    success: "Your account has been closed.",
    error: "Account closure failed. Contact support if this persists.",
  },
  dataExport: {
    title: "Download your data",
    description: "Request a copy of your personal data. You will receive an email with your data within a few minutes.",
    button: "Request data export",
    requesting: "Requesting\u2026",
    success: "Your data export is on its way. Check your email.",
    error: "Data export request failed. Try again.",
  },
  mfa: {
    title: "Two-factor authentication",
    description: "Add a second layer of security to your account using an authenticator app.",
    enabled: "Two-factor authentication is active on this account.",
    disabled: "Two-factor authentication is not enabled.",
    enable: "Enable two-factor authentication",
    disable: "Remove authenticator",
    enrollError: "Could not start enrolment. Try again.",
    enrollSuccess: "Two-factor authentication has been enabled.",
    unenrollError: "Could not remove authenticator. Try again.",
    unenrollSuccess: "Two-factor authentication has been removed.",
    scanQR: "Scan this QR code with your authenticator app.",
    enterCode: "Enter the 6-digit code shown in your app to verify.",
    verifyCode: "Verification code",
    verifyButton: "Verify and enable",
    cancel: "Cancel",
    invalidCode: "Code is incorrect or has expired. Try again.",
  },
  passwordChange: {
    title: "Change password",
    description: "Update the password used to sign in to your account.",
    currentLabel: "Current password",
    newLabel: "New password",
    confirmLabel: "Confirm new password",
    changeCta: "Update password",
    changing: "Updating...",
    tooShort: "Password must be at least 8 characters.",
    mismatch: "Passwords do not match.",
    error: "Password update failed. Try again.",
    success: "Password updated.",
  },
  profileEdit: {
    title: "Profile",
    description: "Update your display name and contact details.",
    fullNameLabel: "Full name",
    phoneLabel: "Phone number",
    whatsappLabel: "WhatsApp number",
    emailLabel: "Email address",
    emailHint: "Email cannot be changed here. Contact support to update your email.",
    saveCta: "Save changes",
    saving: "Saving...",
    success: "Profile updated.",
    error: "Update failed. Try again.",
  },
} as const
