/** Shared actions, nav, date/time, status, currency */

export const commonPrimitives = {
  actions: {
    save: "Save",
    cancel: "Cancel",
    submit: "Submit",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    remove: "Remove",
    create: "Create",
    update: "Update",
    confirm: "Confirm",
    dismiss: "Dismiss",
    retry: "Retry",
    back: "Back",
    next: "Next",
    previous: "Previous",
    done: "Done",
    continue: "Continue",
    export: "Export",
    import: "Import",
    refresh: "Refresh",
  },
  nav: {
    home: "Home",
    dashboard: "Dashboard",
    settings: "Settings",
    profile: "Profile",
    help: "Help",
    signOut: "Sign out",
    signIn: "Sign in",
  },
  dateTime: {
    today: "Today",
    yesterday: "Yesterday",
    tomorrow: "Tomorrow",
    now: "Now",
    justNow: "Just now",
    minutesAgo: "{n} minutes ago",
    hoursAgo: "{n} hours ago",
    daysAgo: "{n} days ago",
    inMinutes: "in {n} minutes",
    inHours: "in {n} hours",
    inDays: "in {n} days",
  },
  status: {
    active: "Active",
    inactive: "Inactive",
    draft: "Draft",
    published: "Published",
    archived: "Archived",
    completed: "Completed",
    inProgress: "In progress",
    cancelled: "Cancelled",
    failed: "Failed",
    scheduled: "Scheduled",
  },
  currency: {
    NGN: "NGN",
    USD: "USD",
    GBP: "GBP",
    EUR: "EUR",
    CAD: "CAD",
    AUD: "AUD",
  },
} as const
