/** Shared UI component primitives — labels, aria, dialogs, etc. */

export const uiPrimitives = {
  labels: {
    invalidDate: "Invalid date",
    metricLoadError: "Unable to load metric",
    clearFilters: "Clear filters",
    loadingContent: "Loading content",
    searchHint: "Search by name, reference number, or status",
    toggleTheme: "Toggle theme",
    dismiss: "Dismiss",
  },
  fileUploader: {
    dropzone: "Drop file here or click to browse",
    releaseToUpload: "Release to upload",
    errorInvalidType: "This file type is not supported",
    errorFileTooLarge: "File must be under 10MB",
    constraintsDefault: "PDF, JPG, PNG · Max 10MB",
  },
  aria: {
    activityTimeline: "Activity timeline",
    pipelineSteps: "Pipeline steps",
    maskedValueShow: "Show value",
    maskedValueHide: "Hide value",
    disbursementProgress: "Disbursement progress",
    hidePassword: "Hide password",
    showPassword: "Show password",
    mobileNavigation: "Mobile navigation",
  },
  statusBadge: {
    pending:          "Pending",
    verified:         "Verified",
    approved:         "Approved",
    rejected:         "Rejected",
    attention:        "Attention needed",
    under_review:     "Under review",
    more_info_needed: "More info needed",
    expiry_soon:      "Expiring soon",
    expired:          "Expired",
    paused:           "Paused",
    frozen:           "Frozen",
    active:           "Active",
    complete:         "Complete",
    locked:           "Locked",
  },
  themeToggle: {
    switchToLight: "Switch to light mode",
    switchToDark: "Switch to dark mode",
  },
  moneyValue: {
    defaultCurrency: "NGN",
  },
  iconAudit: {
    title: "Icon Audit",
    description: "Canonical semantic icon mapping for enterprise routes.",
  },
  dialog: {
    closeSrOnly: "Close",
  },
  trustSignals: {
    kyc: "Your identity data is encrypted and verified through Dojah, a licensed KYC provider. We never store raw identity numbers.",
    bank: "Bank connection is handled securely through Mono. Doculet cannot initiate transactions on your account.",
    certificate: "Your certificate is cryptographically signed and tamper-proof. Recipients can verify authenticity using the unique token.",
  },
  ariaExtended: {
    openMenu: "Open menu",
    closeMenu: "Close menu",
    showPath: "Show path",
    openDialog: "Open dialog",
    closeDialog: "Close dialog",
    expand: "Expand",
    collapse: "Collapse",
    selectAll: "Select all",
    deselectAll: "Deselect all",
    loading: "Loading",
    error: "Error",
    success: "Success",
    treeNavigation: "Tree navigation",
    settingsTabs: "Settings tabs",
    progressSteps: "Progress steps",
    breadcrumbNav: "Breadcrumb",
    breadcrumbNavFull: "Breadcrumb navigation",
    back: "Back",
    dismiss: "Dismiss",
    documentUploadProgress: "Document upload progress",
    pageHelp: "Page help",
    sponsorInvitations: "Sponsor invitations",
  },
  journeyProgress: {
    ariaLabel: "Application progress",
    stepOf: (current: number, total: number) => `Step ${current} of ${total}`,
    nextStep: "Next step",
  },
  searchAutosuggest: {
    tabHint: "Press Tab to accept",
    searching: "Searching...",
  },
  uploadProgress: {
    uploading: "Uploading document",
    scanning: "Scanning for issues",
    processing: "Extracting details",
    submitted: "Submitted for review",
  },
  commandPalette: {
    label: "Command palette",
    placeholder: "Search pages...",
    noResults: "No results found.",
    quickActionsGroup: "Quick actions",
    toggleTheme: "Toggle dark mode",
    goToSettings: "Go to Settings",
  },
  phoneInput: {
    selectCountry: "Select country code",
    label: "Phone number",
    placeholder: "Enter phone number",
    countryCode: "Country code",
  },
  documentPreview: {
    defaultTitle: "Document preview",
    loadError: "Failed to load document preview.",
    retryCta: "Retry",
    unsupportedType: "Preview not available for this file type.",
    downloadCta: "Download",
    openNewTabAriaLabel: "Open in new tab",
  },
  accountDeletion: {
    button: 'Delete account',
    dialogTitle: 'Delete account',
    dialogBody: 'Your account will be scheduled for deletion after a 30-day grace period. Certificates issued remain on the public verification URL.',
    typeToConfirm: 'Type DELETE to confirm',
    confirmPlaceholder: 'DELETE',
    confirm: 'Schedule deletion',
    cancel: 'Cancel',
  },
  sessionTimeout: {
    title: 'Session expiring',
    body: (seconds: number) =>
      `You will be signed out in ${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, '0')} due to inactivity.`,
    dismiss: 'Stay signed in',
    signOut: 'Sign out now',
  },
} as const
